# SPDX-FileCopyrightText: 2026 Julien Y. Dutheil <dutheil@evolbio.mpg.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

theme: jekyll-theme-slate
title: PhySamp
description: Phylogenetic Sampling and Optimization of Sequence Alignments
show_downloads: true
share: true
